-- map applies a function to every element of a list and returns a new list with the results
-- filter applies a function to every element of a list and returns a new list
-- foldr and foldl applies a function from right or left of list all the way to the left or the right
-- sort -> sorts a list
-- zipWith * / + - two lists of equal length lists
-- takeWhile takes elements from a list while a condition is true and returns them
-- dropWhile deletes elements from a list while a condition is true
-- all checks a condition for a list retruns a boolean
-- any checks check a condition for a list returns a boolean